// <auto-generated />
namespace SimpleMembershipExample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DBUserProfilesAddedMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBUserProfilesAddedMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201310062009453_DBUserProfilesAddedMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
